services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 6022:5432
    env_file:
      - .env

  node:
    image: imagem-backend
    build: .
    ports: 
      - 5009:5000
    depends_on:
      - db
    env_file:
      - .env
